In [2]:
import numpy as np
np.array(['1.5','0.62','2','3.14','3.141592'])

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [5]:
str_a1=np.array(['1.567','0.123','5.123','9','8'])
num_a1=str_a1.astype(float)
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [6]:
str_a1.dtype

dtype('<U5')

In [7]:
num_a1.dtype

dtype('float64')

In [9]:
str_a2 = np.array(['1','3','5','7','9'])
num_a2 = str_a2.astype(int)
num_a2


array([1, 3, 5, 7, 9])

In [10]:
str_a2.dtype

dtype('<U1')

In [12]:
num_a2.dtype

dtype('int64')

In [13]:
np.random.rand(2,3)

array([[0.73317237, 0.70288271, 0.40642295],
       [0.4391713 , 0.04766558, 0.07015463]])

In [14]:
np.random.rand()

0.5600648376118497

In [15]:
np.random.rand(2,3,4)

array([[[0.79549992, 0.58864088, 0.15399349, 0.54081634],
        [0.00438089, 0.47917658, 0.67850666, 0.57360715],
        [0.89840467, 0.18897801, 0.13754057, 0.01858663]],

       [[0.60272646, 0.51502268, 0.37675932, 0.1711558 ],
        [0.02088301, 0.26417719, 0.32666339, 0.88784962],
        [0.94121458, 0.23067758, 0.60432213, 0.42016662]]])

In [17]:
np.random.randint(10,size=(3,4))

array([[0, 1, 1, 5],
       [9, 7, 1, 3],
       [9, 2, 7, 2]])

In [19]:
np.random.randint(1,30)

12

In [21]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])

In [22]:
arr1 + arr2

array([11, 22, 33, 44])

In [23]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [24]:
arr2 * 2

array([2, 4, 6, 8])

In [25]:
arr2 **2

array([ 1,  4,  9, 16])

In [26]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [27]:
arr1 / (arr2 **2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

In [28]:
arr1 > 20

array([False, False,  True,  True])

In [30]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [33]:
[arr3.sum(), arr3.mean(), arr3.std(), arr3.var()]

[10, 2.0, 1.4142135623730951, 2.0]

In [34]:
[arr3.min(), arr3.max()]

[0, 4]

In [36]:
arr4 = np.arange(1,5)
arr4

array([1, 2, 3, 4])

In [38]:
[arr4.cumsum(), arr4.cumprod()]

[array([ 1,  3,  6, 10]), array([ 1,  2,  6, 24])]

In [41]:
A = np.array([0,1,2,3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [42]:
B = np.array([3,2,0,1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [43]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [44]:
np.dot(A,B)

array([[0, 1],
       [6, 7]])

In [45]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [46]:
A.transpose()

array([[0, 2],
       [1, 3]])

In [48]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [49]:
np.linalg.det(A)

-2.0

In [50]:
a1 = np.array([0,10,20,30,40,50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [51]:
a1[0]

0

In [53]:
a1[4]

40

In [54]:
a1[5] = 70
a1

array([ 0, 10, 20, 30, 40, 70])

In [55]:
a1[[1,3,4]]

array([10, 30, 40])

In [56]:
a2 = np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [57]:
a2[0,2]

30

In [58]:
a2[2,2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [59]:
a2[1]

array([40, 50, 60])

In [61]:
a2[1] = [47,57,67]
a2

array([[10, 20, 30],
       [47, 57, 67],
       [70, 80, 95]])

In [62]:
a2[[0,2],[0,1]]

array([10, 80])

In [63]:
a = np.array([1,2,3,4,5,6])
a[a > 3]

array([4, 5, 6])

In [64]:
a[(a % 2 == 0)]

array([2, 4, 6])

In [65]:
b1 = np.array([0,10,20,30,40,50])
b1[1:4]

array([10, 20, 30])

In [66]:
b1[:3]

array([ 0, 10, 20])

In [67]:
b1[2:]

array([20, 30, 40, 50])

In [69]:
b1[2:5] =np.array([25,35,45])
b1

array([ 0, 10, 25, 35, 45, 50])

In [70]:
b1[3:6] = 60
b1

array([ 0, 10, 25, 60, 60, 60])

In [71]:
b2 = np.arange(10,100,10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [72]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [73]:
b2[1][0:2]

array([40, 50])

In [75]:
b2[0:2, 1:3] = np.array([[25,35], [55,65]])
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])